install.packages('BiocManager')
BiocManager::install('graph')
BiocManager::install('Bioconductor/RBGL', ref='avoid-Rdefines')
BiocManager::install('ggm')
BiocManager::install('pcalg')
BiocManager::install('kpcalg')
library(devtools)
install_github('Diviyan-Kalainathan/RCIT')
library(RCIT)
